# Generated by Django 2.2.7 on 2019-12-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finity_techserv_portfolio_website_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=264)),
                ('LastName', models.CharField(max_length=264)),
                ('PhoneNo', models.CharField(max_length=264)),
                ('Email', models.EmailField(max_length=264)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
