# Generated by Django 2.2.7 on 2019-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finity_techserv_portfolio_website_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Email', models.EmailField(max_length=264)),
                ('PhoneNo', models.CharField(max_length=264)),
                ('Resume', models.FileField(blank=True, upload_to='Resume')),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
