# Generated by Django 2.2.7 on 2019-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finity_techserv_portfolio_website_app', '0003_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Email', models.EmailField(max_length=264)),
                ('PhoneNo', models.CharField(max_length=264)),
                ('BusinessSector', models.CharField(max_length=500)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='Resume',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
